-- ASSIGNMENT 2
-- AUTHOR: HEMANT THAKKAR, UJJVAL (NUID: 001232511)

-- 1.  WHAT AUTHORS ARE IN CALIFORNIA
SELECT CONCAT(AU_FNAME,' ',AU_LNAME) AS AUTHORNAME,
	   STATE 
FROM   AUTHORS
WHERE  STATE='CA';

-- 2.  LIST THE TITLES AND AUTHOR NAMES
SELECT CONCAT(A.AU_FNAME,' ',A.AU_LNAME) AS AUTHORNAME,
	   T.TITLE AS TITLENAME
FROM   AUTHORS A 
JOIN   TITLEAUTHOR TA ON A.AU_ID=TA.AU_ID 
JOIN   TITLES T ON TA.TITLE_ID=T.TITLE_ID 
ORDER BY AUTHORNAME;

-- 3.  LIST ALL EMPLOYEES AND THEIR JOBS
SELECT CONCAT(E.FNAME,' ',E.LNAME) AS EMPLOYEENAME,J.JOB_DESC 
FROM EMPLOYEE E 
JOIN JOBS J ON E.JOB_ID=J.JOB_ID;

-- 4.  LIST THE TITLES BY TOTAL SALES PRICE
SELECT T.TITLE,SUM(T.PRICE*S.QTY) AS TOTALSALESPRICE 
FROM TITLES T 
JOIN SALES S ON T.TITLE_ID=S.TITLE_ID 
GROUP BY T.TITLE;

-- 5.  FIND THE SALES FOR STORES IN CALIFORNIA
SELECT ST.STOR_NAME,ST.STATE,SUM(SA.QTY) AS TOTALSALES 
FROM STORES ST 
JOIN SALES SA ON ST.STOR_ID=SA.STOR_ID 
WHERE STATE='CA' 
GROUP BY ST.STOR_NAME,ST.STATE;

-- 6.  USE SSMS TO GENERATE A SCRIPT TO CREATE THE AUTHORS TABLE DESCRIBE WHAT THE SCRIPT DOES
USE [PUBS]
GO
/****** OBJECT:  TABLE [DBO].[AUTHORS]    SCRIPT DATE: 23-JAN-17 9:03:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DBO].[AUTHORS](
	[AU_ID] [DBO].[ID] NOT NULL,
	[AU_LNAME] [VARCHAR](40) NOT NULL,
	[AU_FNAME] [VARCHAR](20) NOT NULL,
	[PHONE] [CHAR](12) NOT NULL,
	[ADDRESS] [VARCHAR](40) NULL,
	[CITY] [VARCHAR](20) NULL,
	[STATE] [CHAR](2) NULL,
	[ZIP] [CHAR](5) NULL,
	[CONTRACT] [BIT] NOT NULL,
 CONSTRAINT [UPKCL_AUIDIND] PRIMARY KEY CLUSTERED 
(
	[AU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [DBO].[AUTHORS] ADD  DEFAULT ('UNKNOWN') FOR [PHONE]
GO
ALTER TABLE [DBO].[AUTHORS]  WITH CHECK ADD CHECK  (([AU_ID] LIKE '[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]'))
GO
ALTER TABLE [DBO].[AUTHORS]  WITH CHECK ADD CHECK  (([ZIP] LIKE '[0-9][0-9][0-9][0-9][0-9]'))
GO
/*
The script above does the following:
1)	Creates a table Authors with au_id as the primary key having Primary Key constraint with a Unique Clustered Index. 
2)	It alters the default value of the column PHONE to ‘UNKNOWN’.
3)	It limit the values that can be entered in the columns AU_ID and ZIP  by adding a check constraint.
*/
-- 7.  DESCRIBE WHAT THE AU_ID IS USING FOR A DATA TYPE
-- Datatype: id:varchar(11)
-- ‘id’ is a dictionary datatype defined with varchar as the datatype and having length 11.


-- 8.  LIST THE STORE NAME, TITLE TITLE NAME AND QUANTITY FOR ALL STORES THAT HAVE NET 30 PAYTERMS
SELECT ST.STOR_NAME,T.TITLE,SA.QTY 
FROM TITLES T 
JOIN SALES SA ON T.TITLE_ID=SA.TITLE_ID 
JOIN STORES ST ON ST.STOR_ID=SA.STOR_ID 
WHERE SA.PAYTERMS='NET 30';

-- 9.  FIND THE TITLES THAT DO NOT HAVE ANY SALES SHOW THE NAME OF THE TITLE
SELECT T.TITLE,S.QTY 
FROM TITLES T 
LEFT JOIN SALES S ON T.TITLE_ID=S.TITLE_ID 
WHERE S.QTY IS NULL;

-- 10. DO PREVIOUS QUESTION ANOTHER WAY
SELECT T.TITLE 
FROM TITLES T 
WHERE TITLE_ID 
NOT IN (SELECT TITLE_ID FROM SALES);