package com.neu.datatitans.pojo;
// Generated Apr 27, 2017 9:50:32 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member")
public class Member implements java.io.Serializable {

	private long memberId;
	private String memberFname;
	private String memberLname;
	private boolean memberInsuranceStatus;
	private PersonalInfo personalInfo;
	private MemberAddress memberAddress;
	private MemberPhone memberPhone;

	public Member() {
	}

	public Member(long memberId, String memberFname, String memberLname, boolean memberInsuranceStatus) {
		this.memberId = memberId;
		this.memberFname = memberFname;
		this.memberLname = memberLname;
		this.memberInsuranceStatus = memberInsuranceStatus;
	}

	public Member(long memberId, String memberFname, String memberLname, boolean memberInsuranceStatus,
			 PersonalInfo personalInfo, MemberAddress memberAddress,
			MemberPhone memberPhone) {
		this.memberId = memberId;
		this.memberFname = memberFname;
		this.memberLname = memberLname;
		this.memberInsuranceStatus = memberInsuranceStatus;
		this.personalInfo = personalInfo;
		this.memberAddress = memberAddress;
		this.memberPhone = memberPhone;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "member_id", unique = true, nullable = false, length = 6)
	public long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(long memberId) {
		this.memberId = memberId;
	}

	@Column(name = "member_fname", nullable = false, length = 20)
	public String getMemberFname() {
		return this.memberFname;
	}

	public void setMemberFname(String memberFname) {
		this.memberFname = memberFname;
	}

	@Column(name = "member_lname", nullable = false, length = 20)
	public String getMemberLname() {
		return this.memberLname;
	}

	public void setMemberLname(String memberLname) {
		this.memberLname = memberLname;
	}

	@Column(name = "member_insurance_status", nullable = false)
	public boolean isMemberInsuranceStatus() {
		return this.memberInsuranceStatus;
	}

	public void setMemberInsuranceStatus(boolean memberInsuranceStatus) {
		this.memberInsuranceStatus = memberInsuranceStatus;
	}

	@OneToOne(mappedBy = "member")
	public PersonalInfo getPersonalInfo() {
		return this.personalInfo;
	}

	public void setPersonalInfo(PersonalInfo personalInfo) {
		this.personalInfo = personalInfo;
	}

	@OneToOne(mappedBy = "member")
	public MemberAddress getMemberAddress() {
		return this.memberAddress;
	}

	public void setMemberAddress(MemberAddress memberAddress) {
		this.memberAddress = memberAddress;
	}

	@OneToOne(mappedBy = "member")
	public MemberPhone getMemberPhone() {
		return this.memberPhone;
	}

	public void setMemberPhone(MemberPhone memberPhone) {
		this.memberPhone = memberPhone;
	}

}
