package com.neu.datatitans.pojo;
// Generated Apr 27, 2017 9:50:32 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PersonalInfo generated by hbm2java
 */
@Entity
@Table(name = "personal_info")
public class PersonalInfo implements java.io.Serializable {

	private long memberId;
	private Member member;
	private String ssn;
	private Date dob;
	private String memberProfession;
	private char gender;

	public PersonalInfo() {
	}

	public PersonalInfo(Member member, Date dob, char gender) {
		this.member = member;
		this.dob = dob;
		this.gender = gender;
	}

	public PersonalInfo(Member member, String ssn, Date dob, String memberProfession, char gender) {
		this.member = member;
		this.ssn = ssn;
		this.dob = dob;
		this.memberProfession = memberProfession;
		this.gender = gender;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "member"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "member_id", unique = true, nullable = false, length = 6)
	public long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(long memberId) {
		this.memberId = memberId;
	}

	@OneToOne
	@PrimaryKeyJoinColumn
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "ssn", length = 10)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "member_profession", length = 30)
	public String getMemberProfession() {
		return this.memberProfession;
	}

	public void setMemberProfession(String memberProfession) {
		this.memberProfession = memberProfession;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

}
