package com.neu.datatitans.pojo;
// Generated Apr 27, 2017 9:50:32 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subscriber generated by hbm2java
 */
@Entity
@Table(name = "subscriber")
public class Subscriber implements java.io.Serializable{

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sub_Id", unique = true, nullable = false)
	private long subId;
	
	private String subFullname;
	private String subFname;
	private String subLname;

	public Subscriber() {
	}

	public Subscriber(long subId, String subFullname) {
		this.subId = subId;
		this.subFullname = subFullname;
	}

	public Subscriber(long subId, String subFullname, String subFname, String subLname) {
		this.subId = subId;
		this.subFullname = subFullname;
		this.subFname = subFname;
		this.subLname = subLname;
	}

	
	public long getSubId() {
		return this.subId;
	}

	public void setSubId(long subId) {
		this.subId = subId;
	}

	@Column(name = "sub_fullname", nullable = false, length = 40)
	public String getSubFullname() {
		return this.subFullname;
	}

	public void setSubFullname(String subFullname) {
		this.subFullname = subFullname;
	}

	@Column(name = "sub_fname", length = 20)
	public String getSubFname() {
		return this.subFname;
	}

	public void setSubFname(String subFname) {
		this.subFname = subFname;
	}

	@Column(name = "sub_lname", length = 20)
	public String getSubLname() {
		return this.subLname;
	}

	public void setSubLname(String subLname) {
		this.subLname = subLname;
	}

}
